### ISSUE TITLE
Error: spawn npm ENOENT

### ISSUE THREAD

**Issue by daheadcracker** [ionic-team/migrate-capacitor-plugin#2]
While executing this in the plugin folder e.g. node_modules\@capacitor-community\fcm it correctly updates the @capacitor dependencies of the plugins package.json file to "^5.0.0". But then it stops with:

`Error: spawn npm ENOENT`

I guess this is the reason it also doesn't e.g. update the build.gradle file to put the namespace parameter from the manifest file in it:

`android {
    namespace "com.getcapacitor.community.fcm.fcm"
`

Or it doesn't place this for Android API 33 notifications mandatory permission in the manifest file (if not the plugin author of @capacitor-community\fcm or rather the one of @capacitor/push-notifications should update that in the first place):
`<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>`

As I've read (https://stackoverflow.com/a/27688805/11890464) this could be related to how the subprocess is spawned in migrate-capacitor-plugin/src/subprocess.ts.

Or it has something to do with how my system (windows) is setup?
node: 20.1.0 / npm: 9.6.4 (via nvm)

**Comment by jcesarmobile** [comment]
I have not tested on windows, so maybe it doesn’t work there.

but FYI, I already sent a PR to fcm plugin
https://github.com/capacitor-community/fcm/pull/144

The migrator doesn’t do any code changes in the project, it’s technically not possible to know if a plugin needs new permissions or any other code changes to properly support SDK 33, the migrator just assists with the numerous project changes.
